@startuml
'https://plantuml.com/class-diagram

class Roster
{
    Person: Roster
    readInPeople()
    sortPeople()
    printPeople()
}
class Person
{
    String firstName
    String lastName
    readPerson()
    getFirstName()
    getLastName()
}
Roster->Person
@enduml
