@startuml
'https://plantuml.com/class-diagram

class ex45 
{
    getUser_OutputFile_Name();
}
class Edit 
{
    public String repWord()
    createNewFile(output file name, string output)
}
ex45 <|-- Edit
@enduml
